In [1]:
import numpy as np
from scipy.optimize import minimize
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import pandas as pd
import copy
import os
import random
import math as math
import matplotlib.pylab as plt #Typically matplotlib.pylab is imported as plt (shortened name)
import pdb
from scipy.optimize import minimize
import shutil
import csv
from MyLatexFunctions_SocialLearning import * 
from itertools import permutations 
from itertools import combinations
import csv


import networkx as nx

In [2]:
datafolder = "C:\\Users\\xinxi\\Purdue\\EffectiveSocialLearningProject\\DataAnalysis\\ImportedData\\"

In [3]:
 data = pd.read_csv(datafolder+"p_history.csv", sep=",", header=0)

In [4]:
data['last_infor_content'] = ""
data['num_red'] = 0
data['num_blue'] = 0

In [5]:
for i in range(len(data['p_history'])):
    
    data['last_infor_content'][i] =  data['p_history'][i].split("[[")[1].split("{")[-1].split("},")[0]
    red = 0
    blue = 0
    for x in data['last_infor_content'][i].split(":"):
        if "red" in x :
            red += 1
        if "blue" in x :
            blue += 1
    data['num_red'][i] = red
    data['num_blue'][i] = blue

C:\Users\xinxi\AppData\Local\Temp/ipykernel_8124/2680513950.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['last_infor_content'][i] =  data['p_history'][i].split("[[")[1].split("{")[-1].split("},")[0]
C:\Users\xinxi\AppData\Local\Temp/ipykernel_8124/2680513950.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['num_red'][i] = red
C:\Users\xinxi\AppData\Local\Temp/ipykernel_8124/2680513950.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['num_blue'][i] = blue

In [6]:
data.to_csv(datafolder+"p_history_changed.csv", sep=",")

In [7]:
data

,treatment,waiting_cost,subject_id,round_id,p_history,last_infor_content,num_red,num_blue
0,a L,L,1,17,"[[1, 1, {'D': 'blue', 'A': 'blue'}, 'Blue', 'B...","'D': 'blue', 'A': 'blue'",0,2
1,a L,L,1,18,"[[1, 1, {'D': 'blue', 'A': 'blue'}, 'Blue', 'B...","'D': 'red', 'E': 'blue', 'A': 'red'",2,1
2,a L,L,1,19,"[[1, 1, {'D': 'blue', 'A': 'blue'}, 'Blue', 'B...","'D': 'red', 'E': 'red', 'A': 'red'",3,0
3,a L,L,1,20,"[[1, 1, {'D': 'blue', 'A': 'blue'}, 'Blue', 'B...","'D': 'red', 'E': 'red', 'A': 'blue'",2,1
4,a L,L,1,37,"[[1, 2, {'D': 'blue', 'E': 'red', 'A': 'red'},...","'D': 'blue', 'E': 'red', 'A': 'red'",2,1
...,...,...,...,...,...,...,...,...
3995,b L,L,99,26,"[[1, 0, {'E': 'red'}, 'Red', 'Red', Currency(1...",'E': 'red',1,0
3996,b L,L,99,27,"[[1, 0, {'E': 'red'}, 'Red', 'Red', Currency(1...",'E': 'red',1,0
3997,b L,L,99,28,"[[1, 0, {'B': 'blue'}, 'Blue', 'Blue', Currenc...",'B': 'blue',0,1
3998,b L,L,99,29,"[[1, 0, {'B': 'blue'}, 'Blue', 'Blue', Currenc...",'B': 'blue',0,1
3999,b L,L,99,30,"[[1, 0, {'B': 'blue'}, 'Blue', 'Blue', Currenc...",'B': 'red',1,0