In [1]:
import numpy as np
from scipy.optimize import minimize
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import pandas as pd
import copy
import os
import random
import math as math
import matplotlib.pylab as plt #Typically matplotlib.pylab is imported as plt (shortened name)
import pdb
from scipy.optimize import minimize
import shutil
import csv
from MyLatexFunctions_SocialLearning import * 
from itertools import permutations 
from itertools import combinations
import csv


import networkx as nx

In [4]:
datafolder = "C:\\Users\\xinxi\\Purdue\\EffectiveSocialLearningProject\\DataAnalysis\\ImportedData\\"

In [6]:
 data = pd.read_csv(datafolder+"p_history.csv", sep=",", header=0)

In [106]:
data['last_infor_content'] = ""
data['num_red'] = 0
data['num_blue'] = 0

In [107]:
for i in range(len(data['p_history'])):
    
    data['last_infor_content'][i] =  data['p_history'][i].split("[[")[1].split("{")[-1].split("},")[0]
    red = 0
    blue = 0
    for x in data['last_infor_content'][i].split(":"):
        if "red" in x :
            red += 1
        if "blue" in x :
            blue += 1
    data['num_red'][i] = red
    data['num_blue'][i] = blue

<ipython-input-107-71cab5f7e011>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['last_infor_content'][i] =  data['p_history'][i].split("[[")[1].split("{")[-1].split("},")[0]
<ipython-input-107-71cab5f7e011>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['num_red'][i] = red
<ipython-input-107-71cab5f7e011>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['num_blue'][i] = blue

In [108]:
data.to_csv(datafolder+"p_history_changed.csv", sep=",")

,treatment,waiting_cost,subject_id,p_history,last_infor_content,num_red,num_blue
0,b L,L,101,"[[1, 3, {'A': 'blue', 'B': 'blue', 'C': 'blue'...","'A': 'blue', 'B': 'blue', 'C': 'blue', 'D': 'b...",1,4
1,b L,L,101,"[[1, 3, {'A': 'blue', 'B': 'blue', 'C': 'blue'...","'A': 'red', 'B': 'blue', 'C': 'red', 'D': 'blu...",3,2
2,b L,L,101,"[[1, 3, {'A': 'blue', 'B': 'blue', 'C': 'blue'...","'A': 'blue', 'B': 'blue', 'C': 'red', 'D': 'bl...",1,4
3,b L,L,101,"[[1, 3, {'D': 'red', 'E': 'red', 'A': 'red', '...","'D': 'red', 'E': 'red', 'A': 'red', 'B': 'blue...",3,2
4,b L,L,101,"[[1, 3, {'D': 'red', 'E': 'red', 'A': 'red', '...","'D': 'blue', 'E': 'red', 'A': 'red', 'B': 'blu...",2,3
...,...,...,...,...,...,...,...
2995,b L,L,99,"[[1, 0, {'E': 'red'}, 'Red', 'Red', Currency(1...",'E': 'red',1,0
2996,b L,L,99,"[[1, 0, {'E': 'red'}, 'Red', 'Red', Currency(1...",'E': 'red',1,0
2997,b L,L,99,"[[1, 0, {'B': 'blue'}, 'Blue', 'Blue', Currenc...",'B': 'blue',0,1
2998,b L,L,99,"[[1, 0, {'B': 'blue'}, 'Blue', 'Blue', Currenc...",'B': 'blue',0,1
2999,b L,L,99,"[[1, 0, {'B': 'blue'}, 'Blue', 'Blue', Currenc...",'B': 'red',1,0